### ISSUE TITLE
Upload A11yTO template for the new starter

### ISSUE THREAD

**Issue by nschonni** [accessibility/a11yyow.ca#1]
@touficS asked for the files from Patrick. The should be loaded here and then customized for Ottawa

**Comment by nschonni** [comment]
The content is now there thanks to @TouficS 
@mgifford can you do the DNS changeover and then close this? https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by mgifford** [comment]
I think it's done now. Not 100% sure of the IP address I should use. Hmm..

http://a11yyow.ca/

That gets to github.

**Comment by mgifford** [comment]
$ dig a11yyow.ca +nostats +nocomments +nocmd

; <<>> DiG 9.8.1-P1 <<>> a11yyow.ca +nostats +nocomments +nocmd
;; global options: +cmd
;a11yyow.ca.            IN  A
a11yyow.ca.     3501    IN  A   192.30.252.154
a11yyow.ca.     3501    IN  A   192.30.252.153

That should be working..  I think..

**Comment by nschonni** [comment]
Yeah, it looks like my fork confused it. Working on it now.                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Mike GiffordSent: Friday, October 31, 2014 7:47 AMTo: accessibility/a11yYOW.caReply To: accessibility/a11yYOW.caCc: Nick SchonningSubject: Re: [a11yYOW.ca] Upload A11yTO template for the new starter (#1)$ dig a11yyow.ca +nostats +nocomments +nocmd

; <<>> DiG 9.8.1-P1 <<>> a11yyow.ca +nostats +nocomments +nocmd
;; global options: +cmd
;a11yyow.ca.            IN  A
a11yyow.ca.     3501    IN  A   192.30.252.154
a11yyow.ca.     3501    IN  A   192.30.252.153

That should be working..  I think..

—Reply to this email directly or view it on GitHub.
{"@context":"http://schema.org","@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":"https://github.com/accessibility/a11yYOW.ca/issues/1#issuecomment-61249562","name":"View Issue"}}

**Comment by mgifford** [comment]
It seems to be working so.....
