### ISSUE TITLE
Add new favicon

### ISSUE THREAD

**Issue by nschonni** [accessibility/a11yyow.ca#12]
Site is still showing the cached Drupal version for machines that previously visited.

**Comment by RababGomaa** [comment]
@nschonni  assign this to me

**Comment by nschonni** [comment]
@RubyDo I can't assign anything to you (on GitHub) until you accept the team invitation

**Comment by RababGomaa** [comment]
@nschonni I thought I accepted the invitation last weekend. I will check my email again at work tomorrow

**Comment by RababGomaa** [comment]
@nschonni I accepted the invitation and assigned the issue to myself :) 
(sorry the invitation was misplaced)

**Comment by RababGomaa** [comment]
Done.
