### ISSUE TITLE
Create forms for user submission

### ISSUE THREAD

**Issue by nschonni** [accessibility/a11yyow.ca#4]
If we stick with GH pages, we'll need a work around to do data collection.
One possible solution is https://coderwall.com/p/8lq1ba

**Comment by girafe** [comment]
I suggest we offer a link to email the unconference coordinators. And resist the temptation to steer people toward a format that they must submit to. 

I would be pleased to volunteer to be the receptionist who receives, replies and processes all the incoming messages.
