### ISSUE TITLE
Setup MailChimp for list management

### ISSUE THREAD

**Issue by nschonni** [accessibility/a11yyow.ca#5]
This may already be covered by Meetup, but I noticed the signup on the current site.
MailChimp (free) tier might suit our needs, but I'm not sure of their accessibility.

**Comment by mcman12** [comment]
already setup a mailchimp account, it was used on the a11yyow.ca site.
I'll send the credentials by email.

**Comment by girafe** [comment]
Even though I am a giraffe, I think I could play the monkey’s part. How would ya’ll feel if I was the MailChimp?

**Comment by nschonni** [comment]
Closing since @mcman12 has already set it up as part of the other site

**Comment by girafe** [comment]
I’m very sorry for offering to help with this because I didn’t mean to offend your affair with MailChimp. I know I am too stupid, and I suppose I am only realizing now that machines have replaced my place in the world.

Maybe today a machine will slaughter me and we will all be a peace finally.
