### ISSUE TITLE
Add schedule table

### ISSUE THREAD

**Issue by TouficS** [accessibility/a11yyow.ca#51]
add table with rooms details and time slots 
http://a11yyow.ca/schedule/

**Comment by RababGomaa** [comment]
@TouficS I didn't visit the place so it will be difficult for me to create the table. If you have the info ready I can add the table to the page. Let me know

**Comment by TouficS** [comment]
@RubyDo the table is in the google drive. I will update the talks time after the meeting tomorrow and i will let you know

**Comment by RababGomaa** [comment]
@TouficS  Schedule is online
